"""
Trading Engine - Core trading logic
"""
import logging
import time
from datetime import datetime
from typing import Dict, Optional, List
from dataclasses import dataclass, field
from enum import Enum

from ..strategies.sqz_momentum import calculate_squeeze_momentum
from ..data.data_fetcher import DataFetcher
from .settings import (
    SYMBOLS, CHECK_INTERVAL, MAX_POSITIONS, 
    DEFAULT_CAPITAL_PER_TRADE, MARKET_START_HOUR, MARKET_START_MINUTE,
    MARKET_END_HOUR, MARKET_END_MINUTE
)

logger = logging.getLogger(__name__)


class TradeDirection(Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NONE = "NONE"


class PositionSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


@dataclass
class TradeSignal:
    """Trading signal generated by strategy"""
    symbol: str
    direction: TradeDirection  # LONG or SHORT
    entry_price: float
    timeframe: str = ""  # Timeframe that triggered the signal (e.g., "120m")
    quantity: int = 0
    confidence: float = 0.0  # 0-100
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Position:
    """Active position"""
    symbol: str
    side: PositionSide
    entry_price: float
    quantity: int
    entry_time: datetime
    entry_timeframe: str = ""  # Timeframe in which entry was triggered (e.g., "120m")
    entry_low: float = 0.0  # Low of entry candle for candle-based exit
    current_price: float = 0.0
    pnl: float = 0.0


class TradingEngine:
    """Main trading engine"""
    
    def __init__(self, data_fetcher: DataFetcher, broker=None):
        self.data_fetcher = data_fetcher
        self.broker = broker
        self.positions: Dict[str, Position] = {}
        self.trade_history: List[Dict] = []
        self.is_running = False
        self.total_pnl = 0.0
        
    def check_entry_condition(self, symbol: str) -> Optional[TradeSignal]:
        """
        Check if entry conditions are met for a symbol.
        Returns TradeSignal if entry triggered, None otherwise.
        """
        try:
            # Get latest candle data
            df = self.data_fetcher.get_historical_data(
                symbol, period="5d", interval="5m"
            )
            
            if df is None or len(df) < 25:
                logger.debug(f"Insufficient data for {symbol}")
                return None
            
            # Calculate SQZMOM
            sqz_data = calculate_squeeze_momentum(df)
            
            if "error" in sqz_data:
                logger.debug(f"SQZMOM error for {symbol}: {sqz_data['error']}")
                return None
            
            current_price = self.data_fetcher.get_live_price(symbol)
            if not current_price:
                return None
            
            momentum = sqz_data['momentum']
            prev_momentum = sqz_data['prev_momentum']
            squeeze_state = sqz_data['squeeze_state']
            
            # === ENTRY CONDITIONS (Customize this) ===
            # Entry: Momentum positive + crossing above zero OR squeeze release
            
            # Condition 1: Momentum crossed from negative to positive (bullish signal)
            momentum_turning_positive = (momentum > 0 and prev_momentum < 0)
            
            # Condition 2: Squeeze release (squeeze off with positive momentum)
            squeeze_release = (squeeze_state == "SQUEEZE_OFF" and momentum > 0)
            
            # Condition 3: Strong momentum increase
            strong_momentum = (momentum > prev_momentum and 
                             sqz_data['pct_change'] > 5 and
                             momentum > 0)
            
            if momentum_turning_positive or squeeze_release or strong_momentum:
                quantity = int(DEFAULT_CAPITAL_PER_TRADE / current_price)
                
                if quantity > 0:
                    confidence = 70 if squeeze_release else 60
                    reason = ""
                    if momentum_turning_positive:
                        reason = "Momentum turned positive"
                    elif squeeze_release:
                        reason = "Squeeze release (bullish)"
                    else:
                        reason = "Strong momentum"
                    
                    return TradeSignal(
                        symbol=symbol,
                        direction=TradeDirection.LONG,
                        entry_price=current_price,
                        timeframe="5m",  # Entry triggered in 5m timeframe
                        quantity=quantity,
                        confidence=confidence,
                        reason=reason
                    )
                    
        except Exception as e:
            logger.error(f"Error checking entry for {symbol}: {e}")
            
        return None
    
    def check_exit_condition(self, position: Position) -> Optional[str]:
        """
        Check if exit conditions are met for a position.
        Exit only when a candle in the entry timeframe closes below the previous candle's low.
        Returns exit reason if should exit, None otherwise.
        """
        try:
            current_price = self.data_fetcher.get_live_price(position.symbol)
            if not current_price:
                return None
            
            position.current_price = current_price
            position.pnl = (current_price - position.entry_price) * position.quantity
            
            # Get data for the entry timeframe
            if position.entry_timeframe:
                df = self.data_fetcher.get_data_for_timeframe(
                    position.symbol, position.entry_timeframe
                )
            else:
                # Fallback to 5m if no entry timeframe
                df = self.data_fetcher.get_historical_data(
                    position.symbol, period="5d", interval="5m"
                )
            
            if df is None or len(df) < 2:
                return None
            
            # Check if last closed candle in entry timeframe closed below previous candle's low
            # This is for LONG positions
            if position.side == PositionSide.BUY:
                last_close = df.iloc[-1]['Close']
                prev_low = df.iloc[-2]['Low']
                
                # If last candle closed below previous candle's low, exit
                if last_close < prev_low:
                    return f"Exit: {position.entry_timeframe} candle closed below prev low ({prev_low:.2f})"
            
            # For SHORT positions - exit if candle closes above previous candle's high
            elif position.side == PositionSide.SELL:
                last_close = df.iloc[-1]['Close']
                prev_high = df.iloc[-2]['High']
                
                if last_close > prev_high:
                    return f"Exit: {position.entry_timeframe} candle closed above prev high ({prev_high:.2f})"
                    
        except Exception as e:
            logger.error(f"Error checking exit for {position.symbol}: {e}")
            
        return None
    
    def execute_entry(self, signal: TradeSignal) -> bool:
        """Execute entry trade"""
        if len(self.positions) >= MAX_POSITIONS:
            logger.info(f"Max positions reached, skipping {signal.symbol}")
            return False
        
        if signal.symbol in self.positions:
            logger.info(f"Position already exists for {signal.symbol}")
            return False
        
        try:
            # Get entry candle's low from the entry timeframe
            entry_low = signal.entry_price
            try:
                df = self.data_fetcher.get_data_for_timeframe(signal.symbol, signal.timeframe)
                if df is not None and len(df) > 0:
                    entry_low = df.iloc[-1]['Low']  # Low of last (entry) candle
            except:
                pass
            
            # In real trading, execute with broker
            # For now, just log
            if self.broker:
                # self.broker.place_order(signal)
                pass
            
            position = Position(
                symbol=signal.symbol,
                side=PositionSide.BUY,  # Assuming long for now
                entry_price=signal.entry_price,
                quantity=signal.quantity,
                entry_time=datetime.now(),
                entry_timeframe=signal.timeframe,  # Store the entry timeframe
                entry_low=entry_low,
                current_price=signal.entry_price
            )
            
            self.positions[signal.symbol] = position
            
            logger.info(
                f"🎯 ENTRY: {signal.symbol} | Qty: {signal.quantity} | "
                f"Entry: ₹{signal.entry_price:.2f} | TF: {signal.timeframe} | "
                f"Entry Low: ₹{entry_low:.2f} | Reason: {signal.reason}"
            )
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to execute entry for {signal.symbol}: {e}")
            return False
    
    def execute_exit(self, position: Position, reason: str) -> bool:
        """Execute exit trade"""
        try:
            symbol = position.symbol
            current_price = position.current_price
            
            # Calculate PnL
            pnl = (current_price - position.entry_price) * position.quantity
            self.total_pnl += pnl
            
            logger.info(
                f"🚪 EXIT: {symbol} | PnL: ₹{pnl:.2f} | "
                f"Entry: ₹{position.entry_price:.2f} | "
                f"Exit: ₹{current_price:.2f} | Reason: {reason}"
            )
            
            # Record trade
            self.trade_history.append({
                "symbol": symbol,
                "entry_price": position.entry_price,
                "exit_price": current_price,
                "quantity": position.quantity,
                "pnl": pnl,
                "entry_time": position.entry_time,
                "exit_time": datetime.now(),
                "reason": reason
            })
            
            # Remove position
            del self.positions[symbol]
            
            # In real trading, execute with broker
            # self.broker.place_exit_order(position)
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to execute exit for {position.symbol}: {e}")
            return False
    
    def run(self):
        """Main trading loop"""
        self.is_running = True
        
        logger.info("=" * 50)
        logger.info("Trading Engine Started")
        logger.info(f"Monitoring: {', '.join(SYMBOLS)}")
        logger.info("=" * 50)
        
        while self.is_running:
            try:
                # Check market hours
                if not self.data_fetcher.is_market_open():
                    logger.info("Market closed. Waiting...")
                    time.sleep(60)
                    continue
                
                # Check each symbol for entry
                for symbol in SYMBOLS:
                    if symbol in self.positions:
                        continue  # Already have position
                    
                    signal = self.check_entry_condition(symbol)
                    if signal:
                        self.execute_entry(signal)
                
                # Check each position for exit
                positions_to_exit = []
                for symbol, position in self.positions.items():
                    exit_reason = self.check_exit_condition(position)
                    if exit_reason:
                        positions_to_exit.append((position, exit_reason))
                
                for position, reason in positions_to_exit:
                    self.execute_exit(position, reason)
                
                # Log positions status
                if self.positions:
                    logger.info(f"Active positions: {len(self.positions)}")
                    for symbol, pos in self.positions.items():
                        logger.info(
                            f"  {symbol}: Entry ₹{pos.entry_price:.2f} | "
                            f"Current ₹{pos.current_price:.2f} | PnL ₹{pos.pnl:.2f}"
                        )
                
                time.sleep(CHECK_INTERVAL)
                
            except KeyboardInterrupt:
                logger.info("Stopping trading engine...")
                self.is_running = False
            except Exception as e:
                logger.error(f"Error in trading loop: {e}")
                time.sleep(CHECK_INTERVAL)
        
        logger.info("Trading Engine Stopped")
        logger.info(f"Total PnL: ₹{self.total_pnl:.2f}")
    
    def stop(self):
        """Stop the trading engine"""
        self.is_running = False
        logger.info("Trading engine stop requested")